### ISSUE TITLE
v-select emitting `input` on load

### ISSUE THREAD

**Issue by doublemarked** [TerryZ/v-selectmenu#26]
The component is emitting an `input` event when it loads, which triggers event handlers despite there being no change in model data.

**Comment by TerryZ** [comment]
Fixed in the latest version.

**Comment by doublemarked** [comment]
It took me a while to get around to upgrading and testing this, but in the latest version (v2.0.2) the problem remains.
